### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by BaconWithThat** [aronsky/esphome-components#22]
Trying to add the ble_adv_controller to an existing esphome  chip and I can't compile.

My yaml
`substitutions:
  name: esp32-bluetooth-proxy-ac6528
  friendly_name: Bluetooth Proxy ac6528
packages:
  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: v0ZOqGDhkSoIPkVUi2ULfVfFuY7KTQNgfA0P1ZW8lDY=
external_components:
  source: github://aronsky/esphome-components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ble_adv_controller:
  - id: my_controller
    encoding: lampsmart_pro

light:
  - platform: ble_adv_controller
    ble_adv_controller_id: my_controller
    name: Dining Room Lamp

button:
  - platform: ble_adv_controller
    ble_adv_controller_id: my_controller
    name: Pair
    cmd: pair`

And my relevant logs:
`INFO ESPHome 2024.8.1
INFO Reading configuration /config/esphome/esp32-bluetooth-proxy-ac6528.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esp32-bluetooth-proxy-ac6528 (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
Library Manager: Installing esphome/noise-c @ 0.1.6
INFO Installing esphome/noise-c @ 0.1.6
Unpacking  [####################################]  100%
Library Manager: noise-c@0.1.6 has been installed!
INFO noise-c@0.1.6 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/libsodium @ 1.10018.4
INFO Installing esphome/libsodium @ 1.10018.4
Unpacking  [####################################]  100%
Library Manager: libsodium@1.10018.4 has been installed!
INFO libsodium@1.10018.4 has been installed!
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40407.240606 (4.4.7) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Generating assembly for certificate bundle...
Dependency Graph
|-- noise-c @ 0.1.6
Compiling .pioenvs/esp32-bluetooth-proxy-ac6528/src/esphome/components/api/api_connection.o
Compiling .pioenvs/esp32-bluetooth-proxy-ac6528/src/esphome/components/api/api_frame_helper.o
Compiling .pioenvs/esp32-bluetooth-proxy-ac6528/src/esphome/components/api/api_pb2.o
Compiling .pioenvs/esp32-bluetooth-proxy-ac6528/src/esphome/components/api/api_pb2_service.o
Compiling .pioenvs/esp32-bluetooth-proxy-ac6528/src/esphome/components/api/api_server.o
Compiling .pioenvs/esp32-bluetooth-proxy-ac6528/src/esphome/components/api/list_entities.o
Compiling .pioenvs/esp32-bluetooth-proxy-ac6528/src/esphome/components/api/proto.o
Compiling .pioenvs/esp32-bluetooth-proxy-ac6528/src/esphome/components/api/subscribe_state.o
Compiling .pioenvs/esp32-bluetooth-proxy-ac6528/src/esphome/components/api/user_services.o
Compiling .pioenvs/esp32-bluetooth-proxy-ac6528/src/esphome/components/ble_adv_controller/ble_adv_controller.o
Compiling .pioenvs/esp32-bluetooth-proxy-ac6528/src/esphome/components/ble_adv_controller/ble_adv_handler.o
Compiling .pioenvs/esp32-bluetooth-proxy-ac6528/src/esphome/components/ble_adv_controller/button/ble_adv_button.o
Compiling .pioenvs/esp32-bluetooth-proxy-ac6528/src/esphome/components/ble_adv_controller/fanlamp_pro.o
Compiling .pioenvs/esp32-bluetooth-proxy-ac6528/src/esphome/components/ble_adv_controller/light/ble_adv_light.o
Compiling .pioenvs/esp32-bluetooth-proxy-ac6528/src/esphome/components/ble_adv_controller/zhijia.o
In file included from src/esphome/components/api/proto.h:4,
                 from src/esphome/components/api/api_pb2.h:5,
                 from src/esphome/components/api/user_services.h:8,
                 from src/esphome/components/api/custom_api_device.h:4,
                 from src/esphome/components/ble_adv_controller/light/../ble_adv_controller.h:8,
                 from src/esphome/components/ble_adv_controller/light/ble_adv_light.h:4,
                 from src/esphome/components/ble_adv_controller/light/ble_adv_light.cpp:1:
src/esphome/components/ble_adv_controller/light/ble_adv_light.cpp: In member function 'virtual void esphome::bleadvcontroller::BleAdvLight::dump_config()':
src/esphome/components/ble_adv_controller/light/ble_adv_light.cpp:39:22: error: format '%X' expects argument of type 'unsigned int', but argument 5 has type 'double' [-Werror=format=]
   ESP_LOGCONFIG(TAG, "  Minimum Brightness: 0x%.2X", this->get_min_brightness());
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/core/log.h:72:36: note: in definition of macro 'ESPHOME_LOG_FORMAT'
 #define ESPHOME_LOG_FORMAT(format) format
                                    ^~~~~~
src/esphome/core/log.h:153:33: note: in expansion of macro 'esph_log_config'
 #define ESP_LOGCONFIG(tag, ...) esph_log_config(tag, __VA_ARGS__)
                                 ^~~~~~~~~~~~~~~
src/esphome/components/ble_adv_controller/light/ble_adv_light.cpp:39:3: note: in expansion of macro 'ESP_LOGCONFIG'
   ESP_LOGCONFIG(TAG, "  Minimum Brightness: 0x%.2X", this->get_min_brightness());
   ^~~~~~~~~~~~~
src/esphome/components/ble_adv_controller/light/ble_adv_light.cpp: In member function 'virtual void esphome::bleadvcontroller::BleAdvLight::write_state(esphome::light::LightState*)':
src/esphome/components/ble_adv_controller/light/ble_adv_light.cpp:84:19: error: unknown conversion type character ',' in format [-Werror=format=]
     ESP_LOGD(TAG, "Updating Cold: %.0f%, Warm: %.0f%", cwf*100, wwf*100);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/core/log.h:72:36: note: in definition of macro 'ESPHOME_LOG_FORMAT'
 #define ESPHOME_LOG_FORMAT(format) format
                                    ^~~~~~
src/esphome/core/log.h:152:28: note: in expansion of macro 'esph_log_d'
 #define ESP_LOGD(tag, ...) esph_log_d(tag, __VA_ARGS__)
                            ^~~~~~~~~~
src/esphome/components/ble_adv_controller/light/ble_adv_light.cpp:84:5: note: in expansion of macro 'ESP_LOGD'
     ESP_LOGD(TAG, "Updating Cold: %.0f%, Warm: %.0f%", cwf*100, wwf*100);
     ^~~~~~~~
src/esphome/components/ble_adv_controller/light/ble_adv_light.cpp:84:19: error: spurious trailing '%' in format [-Werror=format=]
     ESP_LOGD(TAG, "Updating Cold: %.0f%, Warm: %.0f%", cwf*100, wwf*100);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/core/log.h:72:36: note: in definition of macro 'ESPHOME_LOG_FORMAT'
 #define ESPHOME_LOG_FORMAT(format) format
                                    ^~~~~~
src/esphome/core/log.h:152:28: note: in expansion of macro 'esph_log_d'
 #define ESP_LOGD(tag, ...) esph_log_d(tag, __VA_ARGS__)
                            ^~~~~~~~~~
src/esphome/components/ble_adv_controller/light/ble_adv_light.cpp:84:5: note: in expansion of macro 'ESP_LOGD'
     ESP_LOGD(TAG, "Updating Cold: %.0f%, Warm: %.0f%", cwf*100, wwf*100);
     ^~~~~~~~
src/esphome/components/ble_adv_controller/light/ble_adv_light.cpp:88:21: error: spurious trailing '%' in format [-Werror=format=]
       ESP_LOGD(TAG, "Updating warm color temperature: %.0f%", updated_ctf*100);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/core/log.h:72:36: note: in definition of macro 'ESPHOME_LOG_FORMAT'
 #define ESPHOME_LOG_FORMAT(format) format
                                    ^~~~~~
src/esphome/core/log.h:152:28: note: in expansion of macro 'esph_log_d'
 #define ESP_LOGD(tag, ...) esph_log_d(tag, __VA_ARGS__)
                            ^~~~~~~~~~
src/esphome/components/ble_adv_controller/light/ble_adv_light.cpp:88:7: note: in expansion of macro 'ESP_LOGD'
       ESP_LOGD(TAG, "Updating warm color temperature: %.0f%", updated_ctf*100);
       ^~~~~~~~
src/esphome/components/ble_adv_controller/light/ble_adv_light.cpp:92:21: error: spurious trailing '%' in format [-Werror=format=]
       ESP_LOGD(TAG, "Updating brightness: %.0f%", updated_brf*100);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/core/log.h:72:36: note: in definition of macro 'ESPHOME_LOG_FORMAT'
 #define ESPHOME_LOG_FORMAT(format) format
                                    ^~~~~~
src/esphome/core/log.h:152:28: note: in expansion of macro 'esph_log_d'
 #define ESP_LOGD(tag, ...) esph_log_d(tag, __VA_ARGS__)
                            ^~~~~~~~~~
src/esphome/components/ble_adv_controller/light/ble_adv_light.cpp:92:7: note: in expansion of macro 'ESP_LOGD'
       ESP_LOGD(TAG, "Updating brightness: %.0f%", updated_brf*100);
       ^~~~~~~~
Compiling .pioenvs/esp32-bluetooth-proxy-ac6528/src/esphome/components/bluetooth_proxy/bluetooth_connection.o
cc1plus: some warnings being treated as errors
Compiling .pioenvs/esp32-bluetooth-proxy-ac6528/src/esphome/components/bluetooth_proxy/bluetooth_proxy.o
*** [.pioenvs/esp32-bluetooth-proxy-ac6528/src/esphome/components/ble_adv_controller/light/ble_adv_light.o] Error 1
========================= [FAILED] Took 12.45 seconds =========================
`

**Comment by NicoIIT** [comment]
Should be solved, please check and close if OK!

**Comment by BaconWithThat** [comment]
Successfully compiled, thank you so much.
